pipeline:
  name: Build go-pipeline-sample
  identifier: Build_StachBandicoot_go_pipeline_sample_1724375786812
  projectIdentifier: HelloWorld
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit test
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: <+input>
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum 
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                      exit 0
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: Run
                  name: Build App
                  identifier: Build_App
                  spec:
                    connectorRef: <+input>
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      CGO_ENABLED=0 GOARCH=amd64 go build -a -tags netgo
                      exit 0
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1724375229094
        repoName: StachBandicoot/go-pipeline-sample
        build: <+input>
        sparseCheckout: []
